### ISSUE TITLE
NoSuchMethodError exception in Android 5.0

### ISSUE THREAD

**Issue by mkulesh** [mkulesh/onpc#105]
The following exception is observed in Android 5.0 and 5.1:

Caused by: java.lang.NoSuchMethodError: No virtual method getActiveNetwork()Landroid/net/Network; in class Landroid/net/ConnectivityManager; or its super classes (declaration of 'android.net.ConnectivityManager' appears in /system/framework/framework.jar:classes2.dex)
        at com.mkulesh.onpc.iscp.ConnectionState.isNetwork(ConnectionState.java:78)
        at com.mkulesh.onpc.iscp.BroadcastSearch.doInBackground(BroadcastSearch.java:103)
        at com.mkulesh.onpc.iscp.BroadcastSearch.doInBackground(BroadcastSearch.java:30)
        at android.os.AsyncTask$2.call(AsyncTask.java:288)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818)

**Comment by mkulesh** [comment]
Released in v1.7
