### ISSUE TITLE
Incomplete message may produce app core in message channel

### ISSUE THREAD

**Issue by mkulesh** [mkulesh/onpc#134]
We observe the situation in message channel where an incomplete message produces a index overflow:
D/onpc: MessageChannel: >> sending: ISCP/v1[16,10]: NTC(LIST) to 192.168.1.80
D/onpc: MessageChannel: << new message NLA from 192.168.1.80, size=108848B, remaining=82B
D/onpc: MessageChannel: << error: unexpected position of message start: -1, remaining=82B
D/onpc: XmlListInfoMsg: << NLA[X0001S000...; RESP=X; SEQ_NR=1; STATUS=S; UI=LIST; XML<63856B>]
D/onpc: XmlListInfoMsg: X0001S000<?xml version="1.0" encoding="utf-8"?><response status="ok"><items offset="0" totalitems="1325" ><item icontype="M" iconid="2d" title="01-Make It.flac"
D/onpc: MessageChannel: << error: invalid raw message: Can not decode raw message: length=82; index=572549474, remaining=1852910987B

As a result, this overflow was a reason of OutOfMemoryError:
W/om.mkulesh.onp: Throwing OutOfMemoryError "Failed to allocate a 1852911000 byte allocation with 10618590 free bytes and 245MB until OOM, target footprint 21237182, growth limit 268435456" (VmSize 5528076 kB)
E/AndroidRuntime: FATAL EXCEPTION: MessageChannel
    Process: com.mkulesh.onpc, PID: 26257
    java.lang.OutOfMemoryError: Failed to allocate a 1852911000 byte allocation with 10618590 free bytes and 245MB until OOM, target footprint 21237182, growth limit 268435456
        at com.mkulesh.onpc.utils.Utils.catBuffer(Utils.java:56)
        at com.mkulesh.onpc.iscp.MessageChannel.processInputData(MessageChannel.java:308)
        at com.mkulesh.onpc.iscp.MessageChannel.run(MessageChannel.java:134)
        at java.lang.Thread.run(Thread.java:919)

**Comment by mkulesh** [comment]
Released in version 2.3
