### ISSUE TITLE
Add support of Multiroom commands

### ISSUE THREAD

**Issue by mkulesh** [mkulesh/onpc#83]
Add support of FlareConnect that is a manufacturer independent protocol to stream audio simultaneously to other compatible devices. It's like Google Cast or Apple AirPlay but made by Onkyo. It'll allow to form groups of devices on demand and play music in multiple rooms without any delay.

**Comment by mkulesh** [comment]
java.util.ConcurrentModificationException
        at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1212)
        at java.util.TreeMap$ValueIterator.next(TreeMap.java:1257)
        at com.mkulesh.onpc.iscp.DeviceList.stop(DeviceList.java:126)
        at com.mkulesh.onpc.iscp.DeviceList.lambda$addToRadioGroup$1(DeviceList.java:248)
        at com.mkulesh.onpc.iscp.-$$Lambda$DeviceList$WLq-pyqGOUfSG00DO0nl2vpupAk.onClick(Unknown Source:4)
        at android.view.View.performClick(View.java:6608)
        at android.widget.CompoundButton.performClick(CompoundButton.java:134)
        at android.view.View.performClickInternal(View.java:6585)
        at android.view.View.access$3100(View.java:782)
        at android.view.View$PerformClick.run(View.java:25945)
        at android.os.Handler.handleCallback(Handler.java:874)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:198)
        at android.app.ActivityThread.main(ActivityThread.java:6729)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)

**Comment by mkulesh** [comment]
Released in v1.4
